### ISSUE TITLE
Vendor Prefixes vs CSS Autoprefixer

### ISSUE THREAD

**Issue by georgiee** [pixari/component-library-monorepo#2]
I think autoprefixer is enabled by default when using vue cli.
So I wonder why this slipped in?

https://github.com/pixari/component-library-monorepo/blob/f16fd34029707705f801f5023d1266ba05768360/packages/my-app/src/App.vue#L22-L23

**Comment by pixari** [comment]
Thank you!
You are right, I don't know as well. :)
I get rid of it.
